exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: true
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: ""
  
title: Jorge Serrano Molina
description: Ese soy yo
